### ISSUE TITLE
FutureProvider ref.watch automatically calling itself

### ISSUE THREAD

**Issue by swarupbhc** [rrousselGit/flutter_hooks#323] opened 2022-08-16 07:26 UTC
**Describe the bug**
FutureProvider ref.watch automatically calling itself

**To Reproduce**

Check the screenshot

**Expected behavior**
wait until it's get called

<img width="1440" alt="Screenshot 2022-08-16 at 12 54 27 PM" src="https://user-images.githubusercontent.com/55395995/184822009-3f223b37-1ecd-4caa-838b-bb1d0d2c1f29.png">

**Comment by rrousselGit** [comment] 2022-08-16 18:40
Could you provide more explanation on what the problem is?

**Comment by rrousselGit** [comment] 2023-02-19 15:05
Closing in the lack of an answer

**Closed by rrousselGit** 2023-02-19 15:05 UTC
Labels: bug, needs triage
