### ISSUE TITLE
Cannot use precacheImage with useMemoized

### ISSUE THREAD

**Issue by cubuspl42** [rrousselGit/flutter_hooks#108] opened 2019-10-29 13:34 UTC
I'm trying to precache an image in my `HookWidget`:

```dart
class TestWidget extends HookWidget {
  TestWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final future =
        useMemoized(() => precacheImage(AssetImage("icon.png"), context));
    return Text("TestWidget");
  }
}
```

This code throws:
```
I/flutter (15245): 'package:flutter_hooks/src/framework.dart': Failed assertion: line 313 pos 12: '!_debugIsInitHook':
I/flutter (15245): is not true.
I/flutter (15245): 
I/flutter (15245): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (15245): more information in this error message to help you determine and fix the underlying cause.
I/flutter (15245): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (15245):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (15245): 
I/flutter (15245): User-created ancestor of the error-causing widget was:
I/flutter (15245):   MaterialApp org-dartlang-app:/main.dart:12:12
I/flutter (15245): 
I/flutter (15245): When the exception was thrown, this was the stack:
I/flutter (15245): #2      HookElement.inheritFromWidgetOfExactType (package:flutter_hooks/src/framework.dart:313:12)
I/flutter (15245): #3      DefaultAssetBundle.of (package:flutter/src/widgets/basic.dart:5391:47)
I/flutter (15245): #4      createLocalImageConfiguration (package:flutter/src/widgets/image.dart:49:32)
I/flutter (15245): #5      precacheImage (package:flutter/src/widgets/image.dart:83:37)
I/flutter (15245): #6      TestWidget.build.<anonymous closure> (package:test1/main.dart:28:27)
I/flutter (15245): #7      _MemoizedHookState.initHook (package:flutter_hooks/src/primitives.dart:36:18)
I/flutter (15245): #8      HookElement._createHookState (package:flutter_hooks/src/framework.dart:473:9)
I/flutter (15245): #9      HookElement._use (package:flutter_hooks/src/framework.dart:376:19)
I/flutter (15245): #10     Hook.use (package:flutter_hooks/src/framework.dart:136:40)
I/flutter (15245): #11     useMemoized (package:flutter_hooks/src/primitives.dart:11:15)
I/flutter (15245): #12     TestWidget.build (package:test1/main.dart:28:9)
I/flutter (15245): #13     _HookWidgetState.build (package:flutter_hooks/src/framework.dart:514:19)
I/flutter (15245): #14     StatefulElement.build (package:flutter/src/widgets/framework.dart:4047:27)
I/flutter (15245): #15     HookElement.build (package:flutter_hooks/src/framework.dart:276:26)
I/flutter (15245): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
I/flutter (15245): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (15245): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter (15245): #19     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
I/flutter (15245): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
[...]
```

Is this behavior expected? If so, how can I precache an image from a `HookWidget`?

**Comment by cubuspl42** [comment] 2019-10-29 14:24
I've learnt that a StatelessWidget shares the same issue, but the exception thrown by Flutter is much more informative.

The solution, for StatefulWidget, is to overload `didUpdateDependencies`. Is there any flutter_hooks way of doing the same thing, without implementing my own `Hook`?

**Comment by smiLLe** [comment] 2019-10-29 14:26
I think the problem is that ```useMemoized()``` acts like initState. So you can't use ```context``` that is listening to an ```InheritedWidget``` which will probably be done by ```precacheImage```.

**Comment by smiLLe** [comment] 2019-10-29 14:29
Creating a custom usePrecacheImage Hook will probably be the easiest way.

**Comment by cubuspl42** [comment] 2019-10-30 09:25
@smiLLe Thank you for your proposed solution. I'm not sure how to implement `usePrecacheImage`, though. In a `StatefulWidget`, I need to override `didUpdateDependencies`. But there's not `didUpdateDependencies` in `Hook`, is there?

**Comment by smiLLe** [comment] 2019-10-30 17:41
it seems like you can call ```precacheImage``` as often as you want for the same Image.
So what you can try is:
```dart
final snapshot = useFuture( precacheImage(AssetImage("icon.png"), context) );
```

Also there is a [didUpdateHook](https://github.com/rrousselGit/flutter_hooks/blob/master/lib/src/primitives.dart#L84) callback that is similar to didUpdateDependencies.

**Comment by rrousselGit** [comment] 2020-02-17 22:43
Closing this since it was answered

**Closed by rrousselGit** 2020-02-17 22:43 UTC

**Comment by cubuspl42** [comment] 2020-02-26 09:49
While the `useFuture` trick might work in practice in some cases, it's a hack. During every build, it creates a new future, which can change the snapshot. The most typical thing to do is to have conditional logic based on snapshot, like...

`return snapshot.hasData ? SomeWidget(snapshot.data) : CircularProgressIndicator()`

It's a bit like hooks alternative to `FutureBuilder`. If `SomeWidget` is stateful and the snapshot is unstable (i.e changes from waiting to resolved, because the future instance changes), then `SomeWidget` initialization logic re-runs. It's definitely not what I want.

I didn't actually test that, but even if that doesn't happen in the current version of Flutter for some reason (maybe `precacheImage` actually returns already-resolved futures?), it's still relying on things that I'd call implementation details.

As far as I understand, `didUpdateHook` mirrors `didUpdateWidget`, not `didUpdateDependencies`, so I don't see how that's relevant.

My team went with hook-less approach for this problem. I don't believe that this issue is actually closed, but it's up to you to decide if you want to re-open it.

**Comment by rrousselGit** [comment] 2020-02-26 09:54
I don't understand what else would you want.

**Comment by cubuspl42** [comment] 2020-02-27 10:42
The problem is clearly stated, and I would love a solution that isn't a hack.

`HookState.didUpdateHookDependencies` sounds like a possible solution.

**Comment by rrousselGit** [comment] 2020-02-27 23:39
I would recommend instead forming the cm function.

You should be able to use `useMemoized` this way by extracting the context usage out of the `useMemoized` callback. 


This will lead to a much more robust solution than using the official `precacheImage` (which is fairly unsafe)

**Comment by edmbn** [comment] 2020-09-02 19:27
I'm sorry for continuing talking about this, but could you @rrousselGit provide a simple example about what you were talking in your las message? Thank you so much!
