### ISSUE TITLE
Timer in HookWidget

### ISSUE THREAD

**Issue by callmejm** [rrousselGit/flutter_hooks#263] opened 2021-09-09 16:23 UTC
Hi, what is the correct way to declare `Timer` in `HookWidget`

`final _detectedTimer = useState<Timer?>(null);`

**Comment by Agondev** [comment] 2021-09-18 17:12
#233 dupe?

**Comment by rrousselGit** [comment] 2021-11-10 12:44
Closing as duplicate of #233

**Closed by rrousselGit** 2021-11-10 12:44 UTC
Labels: enhancement, needs triage
