### ISSUE TITLE
useFuture/useStream: does initialData need to be required?

### ISSUE THREAD

**Issue by PiN73** [rrousselGit/flutter_hooks#229] opened 2021-03-21 18:29 UTC
At 0.16.0 with nullsafety useFuture gets `required T initialData` parameter:
https://github.com/rrousselGit/flutter_hooks/blob/2b02b99ce6b327fd3a6df6f9c52cb2fe791600f6/lib/src/async.dart#L11-L15

This means when there is no initial data, one have to explicitly pass null:
```dart
final snapshot = useFuture(future, initialData: null);
```

Are there any benefits of making it required?

**Comment by PiN73** [comment] 2021-03-21 18:30
One possible benefit would be giving non-nullable type when initialData is provided:
```dart
Future<String> fetchData() {
  return Future.delayed(
    Duration(seconds: 2),
    () => 'Hello',
  );
}

class DisplayData extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final AsyncSnapshot<String> snapshot = useFuture(
      useMemoized(fetchData),
      initialData: '...',
    );
    final String /*!*/ data = snapshot.data;
    return Text(data);
  }
}
```

But AsyncSnapshot class [defines](https://github.com/flutter/flutter/blob/8962f6dc68ec8e2206ac2fa874da4a453856c7d3/packages/flutter/lib/src/widgets/async.dart#L242) data as `T?` so we lose non-nullable type anyway

**Comment by rrousselGit** [comment] 2021-03-21 18:32
It is necessary, because otherwise `snapshot.requireData` would be `T?` instead of `T`

**Comment by rrousselGit** [comment] 2021-03-21 18:33
Considering the nature of hooks, you could use make a `useNullableFuture` that wraps `useFuture` to make `T` nullable

**Comment by PiN73** [comment] 2021-03-21 18:38
> It is necessary, because otherwise `snapshot.requireData` would be `T?` instead of `T`

Yes, but `T` doesn't seem stronger than `T` here because even if it's `T`, `snapshot.data` will be `T?` anyway

**Comment by rrousselGit** [comment] 2021-03-21 20:41
This isn't about "snapshot.data" but "snapshot.requireData"

**Comment by PiN73** [comment] 2021-03-21 21:22
Well, but my message is that `snapshot.data` is `T?` anyway. It is [defined](https://github.com/flutter/flutter/blob/8962f6dc68ec8e2206ac2fa874da4a453856c7d3/packages/flutter/lib/src/widgets/async.dart#L242) in flutter/lib/src/widgets/async.dart -> `class AsyncSnapshot<T>` as
```dart
final T? data;
```

**Comment by kasperpeulen** [comment] 2021-03-22 07:41
I think one way you could think of this, is that AsyncSnapshot is an Either<Object, T>. The implementation of requireData seems to hint at that. It assumes that it *either* contains data of type T or an error of of type Object.

Now if you are sure that this Stream or Future never fails (because you just put values in the StreamController for example), or you want to handle errors higher up the tree, you can use requireData, and safely get the T out of the Either<Object, T>. In your example @PiN73 you could use requireData, as your Future will never fail.

Now of course this is all quite shitty and with sealed classes or unions, AsyncSnapshot could be implemented much more sensible and transparant. 

Also, I think if you have a Future, Stream that never fails, then wrapping it in snapshot object (basically wrapping it in an Either), is an overkill. Maybe we could define usePureFuture, usePureStream for those cases.

**Comment by rrousselGit** [comment] 2021-03-28 14:34
> Well, but my message is that snapshot.data is T? anyway

Yes

But the reasoning behind `T` instead of `T?` is unrelated to `data` and is instead of `requireData`.

**Comment by peterweb2005** [comment] 2021-03-30 19:55
also, copied from other issue

```
Store<State, Action> useReducer<State, Action>(
  Reducer<State, Action> reducer, {
  required State initialState,
  required Action initialAction, // did initialAction "required"?
}) {
```

did initialAction "required"?

**Comment by micimize** [comment] 2021-04-04 23:38
[`requireData`](https://github.com/flutter/flutter/blob/8962f6dc68ec8e2206ac2fa874da4a453856c7d3/packages/flutter/lib/src/widgets/async.dart#L248-L254) returns `data!`, so the problem is probably more that [this call to `AsyncSnapshot<T>.withData` would set the type to `T?`](https://github.com/rrousselGit/flutter_hooks/blob/6d590cd3204f0978b3d9cdc23435a5e279c73f55/packages/flutter_hooks/lib/src/async.dart#L212-L213). So, this might work for nullable `initialData`:
```dart
hook.initialData != null ?
  AsyncSnapshot<T>.withData(ConnectionState.none, hook.initialData!) :
  AsyncSnapshot<T>.waiting();
  // maybe also widget.stream == null ?  AsyncSnapshot<T>.nothing();
```

**Comment by shilangyu** [comment] 2021-04-06 19:47
I have a rather hard time understanding why initialData is a `required T` rather than just `T?`.

Here is a small example. I have some future that will eventually turn into an `int`. Obviously, I don't really have any initial data since that's the point, I am fetching it and subscribing to changes with `useFuture`. Then I proceed to handle the error and no-data-yet case and then assert that I guarantee that data will be now available if the previous checks are false. Then I pass the asserted data into a function that takes a non-nullable. But this wont work! Because `initialData` is `T` instead of `T?` it forces the return type of `useFuture` to be `AsyncSnapshot<T?>` so `.requireData` effectively turns a `T??` into `T?`. In `AsyncSnapshot` `.data` is already `T?` so I don't see why am I forced to make provide an `initialData` as a `T`


```dart
int doubleMe(int n) => 2 * n;

Future<int> apiData = Future.value(42);

class SomeWidget extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final dataSnapshot = useFuture(apiData, initialData: null);

    if (dataSnapshot.hasError) return Center(child: Text('error'));
    if (!dataSnapshot.hasData) return Center(child: Text('loading'));

    final data = dataSnapshot.requireData;

    doubleMe(data);

    return Container();
  }
}
```

Am I missing something?

**Comment by rrousselGit** [comment] 2021-04-06 21:05
> [`requireData`](https://github.com/flutter/flutter/blob/8962f6dc68ec8e2206ac2fa874da4a453856c7d3/packages/flutter/lib/src/widgets/async.dart#L248-L254) returns `data!`,

That's a bug (combined with the `hasData` being `data != null`) and there were some discussions in the past on how to fix it

It should be possible for `Future.value(null)` to resolve with `hasData: true` and `requireData == null`

We _could_ support it, but if `hasData`/`requireData` are updated to fix this bug, that'll require flutter_hooks to make a breaking change – which I'm not super fond of.

**Comment by AAverin** [comment] 2021-04-17 10:02
What if underlying Future is returning void?
`useFuture(voidReturningFuture())` would make sense because there is no initial data.

use case would be to do something asynchronous during build, like tracking a page view.

**Comment by micimize** [comment] 2021-04-19 14:46
If `initialData` is nullable for the convenience of one use-case, it is detrimental for the other. There is no way around this. The maintainer has provided good rationale for the current design aside from that, which is that it is the most accommodating to both completeness, and compatibility with potential implementation changes in `async` currently under discussion.

So, I don't think this should be changed unless dart adds [function overloading](https://github.com/dart-lang/language/issues/1122). Creating a user land helper is so exceedingly trivial:
```dart
AsyncSnapshot<T?> useStreamN<T>(Stream<T?> s, {T? initialData = null}) => useStream(s, initialData: initialData);
```

**Comment by AAverin** [comment] 2021-04-19 15:01
@micimize This will not work if future returns void, because `void` is not type `Null`. And it's also not possible to use `Void` class because `void` is not type `Void`

**Comment by AAverin** [comment] 2021-04-20 05:26
@micimize I am still not on latest Dart, maybe that's the reason. Will have to try after all of the dependencies provide null safety support.

**Comment by jaumard** [comment] 2021-04-27 10:36
That required `initialData` is really really painful... We just can't use simple syntaxe anymore...
```
final AsyncSnapshot<PaginateCashAdvanceHistory> history = useStream(bloc.history, initialData: null);
```
And if I'm using BLoC I can't even use useFuture or anything... I'm just fucked or force to put it nullable where I know it can't once load. 

Also I always seen useStream as a replacement of StreamBuilder, and StreamBuilder doesn't force you to put initialData at all.

**Comment by jaumard** [comment] 2021-05-18 14:30
Hey, just testing the version containing the fix, so now it forces nullable on the snapshot even if the given stream can't have null values... I would say that it's even worse than before no ??

**Comment by rrousselGit** [comment] 2021-05-18 14:57
Isn't that what people asked for?

I was originally against it because of this.

**Comment by jaumard** [comment] 2021-05-18 15:05
Ha ha I don't know for other people but on my side I was expecting same behavior as StreamBuilder.

Meaning I can do that without issue: 
```
StreamBuilder<bool>(
                    stream: loginBloc.canContinue,
                    builder: (context, AsyncSnapshot<bool> snapshot) {
                      return ...;
                   })
                  
```

But currently I can't do that:
```
final AsyncSnapshot<bool> snapshot = useStream(loginBloc.canContinue);
```

Because before initialState was mandatory, now before it force by default `AsyncSnapshot<bool?>`

Is that more clear ? Don't mind making a quite call about this if it help

**Comment by PiN73** [comment] 2021-05-18 18:31
@jaumard the motivation of making `useStream` return `AsyncSnapshot<T?>` was the fact that `snapshot.data` is `T?` anyway — even for `AsyncSnapshot<T>`.

To make `AsyncSnapshot<T>` possible for convenience but also keep `initialData` optional in default `useStream` implementation I propose #243. @rrousselGit what do you think about it?

**Comment by rrousselGit** [comment] 2021-05-19 07:42
I'm not fan of it.

Apparently `StreamBuilder` works around the issue by doing:

```dart
initialData == null
      ? AsyncSnapshot<T>.nothing()
      : AsyncSnapshot<T>.withData(ConnectionState.none, initialData as T)
```

If someone wants to make a PR with this change, I'd be happy to review it

**Comment by jaumard** [comment] 2021-05-19 09:50
I'll try to do the PR thanks @rrousselGit, to me make much more sens :)

**Comment by jaumard** [comment] 2021-05-19 09:51
can this be reopen until new PR is done and merged  ?

**Comment by rich-j** [comment] 2021-05-19 17:47
We generally specify types and provide initial values:

```dart
    final Future<String> somedayAString = Future.value("A string");
    final String aString = useFuture(somedayAString, initialData: "").requireData;
```

Upgrading to `0.17.0` now gives us:

```
error: A value of type 'String?' can't be assigned to a variable of type 'String'.
```

Yes a "`!`" will fix it but we try to avoid type casts. Reverting to `0.16.0` until this is fixed. Thanks.

**Closed** 2021-06-30 11:12 UTC
